### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [thekristisha/KristinaSerikova#6]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий

**Нужно исправить** файл README должен содержать заголовок и описание **отражающие суть проекта**.

**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

### Имя
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`ААнна-ММария - в имени допустима только 1 заглавная буква. В двойных 2 заглавных буквы, каждая из которых в начале соответствующей части имени
`Денис-` (дефис, нет двойного имени, допустимо либо Денис, либо Денис-Иван)
`Денис-ловеркейс` (второе имя должно быть с заглавной буквы)

### Email
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным

### Номер телефона

**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
```
+7(925 900-90-90
+7925900-90-90
+792590090-90
+7-925-900-90-90
+7(925) 9009090
+7(925)9009090
+7 925 900-90-90
```

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию

`http://www.ya.` - отсутствует доменная зона
`http://www` - отсутствует доменная зона и доменное имя
`http://.ru` - отсутствует доменное имя 
`http://1.` - некорректный IP, точка на конце
`http://127.0..`  - некорректный IP, точка на конце
`http://127.0.0..` - некорректный IP, точка на конце

**Можно лучше** следующие некорректные кейсы проходят валидацию

`http://www.google.ru///////` - в пути количество слешей подряд должно быть ограничено 1

**Comment by thekristisha** [comment]
Ожидает проверки

**Comment by zlocate** [comment]
Добрый вечер. Благодарю за оперативное внесение правок.
Осталось 2 кейса. требующих исправления:

## Регулярные выражения
### Имя
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`ААнна` - имя может содержать только одну заглавную букву в каждой части

### Адрес сайта
`http://127.0.0.1:8000/$ssss@#` - некорректный путь - разрешены только цифры, слеш и латинские буквы, решетка (#) на конце

**Comment by thekristisha** [comment]
Ожидает проверки

**Comment by zlocate** [comment]
Добрый вечер. В текущей версии не проходит проверку следующий кейс

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`http://x.com `- доменное имя может состоять из одной буквы

**Comment by thekristisha** [comment]
Добрый вечер. Ожидает проверки

**Comment by zlocate** [comment]
Работа принята. Желаю успехов в дальнейшем прохождении курса :)
